version: '3.8'

services:
  web:
    container_name: web_test
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.test
    depends_on:
      - db
    platform:
      linux/amd64
  db:
    container_name: db_test
    image: postgres:14.0-alpine
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pyforge
      - POSTGRES_PASSWORD=pyforge
      - POSTGRES_DB=pyforge
volumes:
  postgres_data: